interface Resources {
  actions: {
    accept: 'Accept';
    add: 'Add';
    cancel: 'Cancel';
    cancelBooking: 'Cancel Booking';
    cancelUpload: 'Cancel Upload';
    changeDates: 'Change Dates';
    changeStatus: 'Change Status';
    'confirm-booking': 'Confirm Booking';
    create: 'Create';
    'create-user': 'Create user';
    'create-yacht': 'Create Custom Boat';
    creating: 'Creating...';
    delete: 'Delete';
    'delete-booking': 'Cancel Booking';
    'delete-custom-boat': 'Delete custom boat';
    deleteInquiry: 'Delete Inquiry';
    deleteInvoice: 'Delete Invoice';
    deleteUser: 'Delete User';
    discard: 'Discard';
    'discard-changes': 'Discard changes';
    download: 'Download';
    'download-pdf': 'Download PDF';
    edit: 'Edit';
    'edit-notes': 'Edit notes';
    save: 'Save';
    sort: 'Sort';
    clear: 'Clear';
    editUser: 'Edit User';
    filter: 'Filter';
    'generate-invoice': 'Generate Invoice';
    'mark-as-paid': 'Mark as Paid';
    markAsSent: 'Mark as Sent';
    markAsSentInvoice: 'Mark as Sent Invoice';
    reject: 'Reject';
    reset: 'Reset';
    search: 'Search';
    sendInvoice: 'Send Invoice';
    sendOffer: 'Send Offer';
    'sync-booking': 'Sync Booking';
    update: 'Update';
    'update-yacht': 'Update Custom Boat';
    updateInvoice: 'Update invoice';
    updating: 'Updating...';
    uploaded: 'uploaded';
  };
  amenities: {
    BBQ: 'BBQ';
    'DVD-player': 'DVD Player';
    'air-conditioning': 'Air conditioning';
    'audio-system': 'Audio system';
    autopilot: 'Autopilot';
    'bathing-platform': 'Bathing platform';
    bicycle: 'Bicycle';
    bimini: 'Bimini';
    'bow-thruster': 'Bow thruster';
    'coffee-machine': 'Coffee machine';
    cooker: 'Cooker';
    dinghy: 'Dinghy';
    dishwasher: 'Dishwasher';
    'electric-winches': 'Electric winches';
    'fishing-set': 'Fishing set';
    'flat-screen-TV': 'Flat screen TV';
    flybridge: 'Flybridge';
    freezer: 'Freezer';
    fridge: 'Fridge';
    'game-console': 'Game console';
    generator: 'Generator';
    gennaker: 'Gennaker';
    heating: 'Heating';
    'ice-maker': 'Ice maker';
    'inside-speakers': 'Inside speakers';
    inverter: 'Inverter';
    jacuzzi: 'Jacuzzi';
    'jet-ski': 'Jet ski';
    karaoke: 'Karaoke';
    kayak: 'Kayak';
    'kitchen-utensils': 'Kitchen utensils';
    microwave: 'Microwave';
    'outside-GPS-plotter': 'Outside GPS plotter';
    'outside-shower': 'Outside shower';
    'outside-speakers': 'Outside speakers';
    oven: 'Oven';
    'pillows-and-blankets': 'Pillows and blankets';
    radar: 'Radar';
    'safety-net': 'Safety net';
    'salon-GPS-plotter': 'Salon GPS plotter';
    shower: 'Shower';
    sink: 'Sink';
    'snorkel-sets': 'Snorkel sets';
    'solar-panels': 'Solar panels';
    spinnaker: 'Spinnaker';
    'stand-up-paddle': 'Stand Up Paddle';
    'sun-pads': 'Sun pads';
    surf: 'Surf';
    'teak-deck': 'Teak deck';
    towels: 'Towels';
    wakeboard: 'Wakeboard';
    'washing-machine': 'Washing machine';
    'waste-tank': 'Waste tank';
    'water-maker': 'Water maker';
    'water-skis': 'Water skis';
    'water-toys': 'Water toys';
    windsurf: 'Windsurf';
  };
  booking: {
    'additional-paid-at-marina': 'Additional - Paid at marina';
    'additional-paid-now': 'Additional - Paid now';
    'admin-notes': 'Internal notes';
    'admin-notes-hint': 'Visible to admins only — never shown to the customer.';
    'admin-notes-placeholder': 'e.g. Customer needs airport transfer; paid 500 EUR cash; call before check-in...';
    'apa-description': 'Lorem ipsum';
    'apa-text': '{{value}} price without VAT';
    'booking-info': 'Booking Info';
    'cancel-booking': 'Cancel Booking';
    'cancellation-reason': 'Reason';
    'cancellation-requested': 'Cancellation Requested';
    'cancellation-requested-on': 'Cancellation requested on';
    'change-status': 'Change Status';
    'charter-company': 'Charter company';
    'check-in': 'Check-in';
    'check-out': 'Check-out';
    'client-price': 'Client price';
    'confirm-booking': 'Confirm Booking';
    day: 'day';
    days: 'days';
    'guest-info': 'Guest Info';
    included: 'Included';
    'manage-booking': 'Manage Booking';
    'marina-total': 'Total to pay at marina';
    'refundable-security-deposit': 'Refundable security deposit';
    'refundable-security-deposit-hint': 'Held at pick-up, returned on damage-free return';
    'deposit-insurance': 'Deposit insurance';
    'crew-list-url': 'Crew list URL';
    'crew-list-url-placeholder': 'https://...';
    save: 'Save';
    saving: 'Saving...';
    documents: {
      title: 'Documents';
      'internal-title': 'Internal documentation';
      empty: 'No documents attached yet.';
      loading: 'Loading…';
      uploading: 'Uploading…';
      'drop-now': 'Drop to upload';
      'drop-or-click': 'Drop files here or click to upload';
      'types-hint': 'PDF, DOC, DOCX up to 20 MB';
      open: 'Open document';
      download: 'Download';
      delete: 'Delete';
      'confirm-delete': 'Delete "{{filename}}"? This cannot be undone.';
    };
    'mark-as-paid': 'Mark as Paid';
    'not-paid': 'Not paid';
    obligatory: 'Obligatory';
    'obligatory-paid-at-marina': 'Obligatory - Paid at marina';
    'obligatory-included': 'Obligatory - Included in price';
    paid: 'Paid';
    'paid-at-marina': 'Paid at marina';
    'paid-now': 'Paid now';
    'payment-phases': 'Payment Phases';
    phase: 'Phase';
    'pickup-location': 'Pick-up location';
    'please-dont-close-window': 'Please keep this window open while the reservation is syncing';
    'price-information': 'Price Information';
    'special-request': 'Special Request';
    'sync-booking': 'Sync Booking';
    'sync-booking-text': 'Are you sure you want to sync booking {{value}}? Doing this action cannot be reverted.';
    total: 'Total';
    'update-booking': 'Update this booking';
    'view-boat': 'View boat';
    'your-booking-is-sync': 'Your booking is <strong>being synced!</strong>';
  };
  common: {
    accepted: 'Accepted';
    'access-denied': 'Access Denied';
    'access-denied-description': 'You don’t have permission to view this page. <br /> If you believe this is a mistake, contact your administrator.';
    active: 'Active';
    'add-more': 'Add more';
    addUser: 'Add User';
    agencies: 'Agencies';
    agency: 'Agency';
    all: 'All';
    answered: 'Answered';
    archived: 'Archived';
    blacklisted: 'Blacklisted';
    bookings: 'Bookings';
    browse: 'Browse';
    browsePdf: 'or browse for .pdf document';
    browsePhoto: 'or browse for photos';
    cancel: 'Cancel';
    cancelled: 'Cancelled';
    clear: 'Clear';
    company: 'Company';
    completed: 'Completed';
    'confirm-booking-text': 'Are you sure you want to confirm booking {{value}}? Doing this action cannot be reverted.';
    confirmed: 'Confirmed';
    country: 'Country';
    createInvoice: 'Create Invoice';
    croatian: 'Croatia';
    customBoats: 'Custom Boats';
    customer: 'Customer';
    dateRange: 'Date Range';
    'delete-confirmation-text-bulk': 'Are you sure you want to delete {{value}}? This action cannot be undone.';
    departureDate: 'Departure Date';
    details: 'Details';
    'discard-changes-description': 'Are you sure you want to discard your changes?';
    'discount-not-applicable': 'The discount does not apply to the selected boats.';
    draft: 'Draft';
    dragAndDrop: 'Drag and drop';
    edit: 'Edit';
    english: 'English';
    equipment: 'Equipment';
    amenities: 'Amenities';
    extras: 'Extras';
    financials: 'Financials';
    'general-info': 'General Information';
    'high-tier': 'High Tier Pricing';
    inactive: 'Inactive';
    inquiries: 'Inquiries';
    'inquiries-status': 'Inquiries Status';
    'invalid-credentials': 'Incorrect email or password.';
    'invite-send-to-email': 'An invite will be sent to user’s email to confirm the account,';
    invited: 'Invited';
    invoice: 'Invoice';
    invoices: 'Invoices';
    'low-tier': 'Low Tier Pricing';
    'main-image': 'Main image';
    'manual-entry-noter': "Can't find your manufacturer or model? Enter them manually below to create new entries.";
    'mark-sent-text': 'Are you sure you want to mark as sent {{value}}? This action cannot be undone.';
    maxDiscount: 'Maximum Discount';
    'mid-tier': 'Mid Tier Pricing';
    mmk: 'MMK';
    nausys: 'Nausys';
    new: 'New';
    no: 'No';
    'no-matches': 'No matches';
    'no-records': 'No records were found.';
    'not-found': 'Page Not Found';
    'not-found-description': 'The page you’re looking for doesn’t exist. <br /> Check the URL or go back to the homepage.';
    notInvited: 'Not invited';
    option: 'Option';
    optionWaiting: 'Option Waiting';
    paymentStatus: 'Payment Status';
    'pdf-upload': 'PDF Upload';
    pending: 'Pending';
    photos: 'Photos';
    pricing: 'Pricing';
    'primary-source': 'Primary source';
    'private-person': 'Private person';
    profile: {
      'account-settings': 'Account Settings';
      'card-surcharge': 'Card Payment Surcharge (%)';
      'card-surcharge-description': 'Additional fee charged for card payments (e.g., 2.5 for 2.5%)';
      'current-card-surcharge': 'Current Card Payment Surcharge';
      'current-email': 'Current Email';
      'current-password': 'Current Password';
      'delete-account': 'Delete account';
      email: 'Email';
      'email-description': 'Make sure you have access to this email address.';
      'full-name': 'Full Name';
      'full-name-description': 'Make sure this matches the name on your ID';
      'input-card-surcharge': 'Enter card payment surcharge';
      'input-email': 'Input email';
      'input-new-password': 'Input New Password';
      'input-password': 'Input Password';
      'last-name': 'Last Name';
      name: 'Name';
      'new-password': 'New Password';
      password: 'Password';
      'password-description': 'Change password';
      'repeat-new-password': 'Repeat New Password';
      'repeat-password': 'Repeat Password';
    };
    recipientType: 'Recipient Type';
    reservation: 'Reservation';
    reservationManager: 'Reservation Manager';
    result_one: '{{count}} item';
    result_other: '{{count}} items';
    save: 'Save';
    saving: 'Saving...';
    sent: 'Sent';
    systemAdmin: 'System Admin';
    unknown: 'Unknown';
    user: 'User';
    'user-status': 'User Status';
    users: 'Users';
    video: 'Video';
    yes: 'Yes';
  };
  extras: {
    'adrenalin-pack': 'Adrenaline pack';
    'adrenalin-pack-description': 'High-energy water sports equipment package';
    'airstream-towable': 'Airstream towable';
    'airstream-towable-description': 'Premium inflatable for high-speed towing activities';
    apa: 'APA (advance provisioning allowance)';
    'apa-description': 'Advance payment for fuel, food, drinks, and port fees';
    'banana-boat': 'Banana boat';
    'banana-boat-description': 'Fun inflatable ride for multiple passengers';
    'beach-towels': 'Beach towels';
    'beach-towels-description': 'Special towels for beach and water activities';
    'coffee-machine': 'Coffee Machine';
    'coffee-machine-description': 'Professional coffee machine for fresh coffee during your trip';
    cook: 'Cook / Chef';
    'cook-description': 'Professional chef to prepare meals during your charter';
    'deposit-insurance': 'Deposit insurance';
    'deposit-insurance-description': 'Insurance coverage to protect your security deposit';
    'dinghy-outboard-engine': 'Dinghy with outboard engine';
    'dinghy-outboard-engine-description': 'Motorized tender for easy transportation to shore';
    'diving-equipment': 'Diving equipment';
    'diving-equipment-description': 'Complete scuba diving gear including tanks and regulators';
    donut: 'Donut tube';
    'donut-description': 'Inflatable ring for fun water activities and relaxation';
    'early-boarding': 'Early boarding / Check-in';
    'early-boarding-description': 'Board the yacht before standard check-in time';
    efoil: 'E-foil board';
    'efoil-description': 'Electric hydrofoil board for surfing above the water';
    'family-pack': 'Family pack';
    'family-pack-description': 'Special package designed for families with children';
    'fishing-equipment': 'Fishing equipment';
    'fishing-equipment-description': 'Complete fishing gear including rods, reels, and tackle';
    'floating-mats': 'Floating mats';
    'floating-mats-description': 'Large floating platforms for relaxation on water';
    grill: 'Grill / Barbecue';
    'grill-description': 'Outdoor cooking equipment for grilling and barbecuing';
    hostess: 'Hostess';
    'hostess-description': 'Crew member responsible for guest services and cabin maintenance';
    'inflatable-lifejacket': 'Inflatable lifejacket';
    'inflatable-lifejacket-description': 'Additional safety equipment for water activities';
    'inflatable-swimming-platform': 'Inflatable swimming platform';
    'inflatable-swimming-platform-description': 'Additional floating platform for swimming and relaxation';
    'jet-ski': 'Jet ski';
    'jet-ski-description': 'Personal watercraft for high-speed water adventures';
    kayak: 'Kayak';
    'kayak-description': 'Single or double kayak for exploring coastlines and coves';
    kneeboard: 'Kneeboard';
    'kneeboard-description': 'Board for kneeboarding water sports activities';
    'larger-rib': 'Larger RIB / Dinghy';
    'larger-rib-description': 'Bigger tender with more capacity and better performance';
    'late-boarding': 'Late boarding / Check-in';
    'late-boarding-description': 'Flexible check-out time beyond standard hours';
    'mono-skis': 'Mono skis';
    'mono-skis-description': 'Single water ski for advanced water skiing';
    'permit-for-montenegro': 'Permit for Montenegro';
    'permit-for-montenegro-description': 'Required documentation for sailing in Montenegrin waters';
    'pets-onboard': 'Pets onboard';
    'pets-onboard-description': 'Permission and accommodation for your pets during the charter';
    'refundable-security-deposit': 'Refundable security deposit';
    'refundable-security-deposit-description': 'Security deposit that will be returned if no damages occur';
    'safety-net': 'Safety net';
    'safety-net-description': 'Safety nets installed around the yacht for enhanced security';
    seabob: 'Seabob';
    'seabob-description': 'High-tech underwater scooter for diving and surface riding';
    skipper: 'Skipper service';
    'skipper-description': 'Professional crew member who operates and navigates the yacht';
    'snorkeling-equipment': 'Snorkeling equipment';
    'snorkeling-equipment-description': 'Masks, fins, and snorkels for underwater exploration';
    'stand-up-paddle-SUP': 'Stand up paddle (SUP)';
    'stand-up-paddle-SUP-description': 'Paddleboard equipment for water sports and recreation';
    subwing: 'Subwing board';
    'subwing-description': 'Underwater wings for gliding beneath the surface';
    'tourist-tax': 'Tourist tax';
    'tourist-tax-description': 'Local government fees required for visiting certain destinations';
    towels: 'Towels';
    'towels-description': 'Clean towels provided for your comfort during the charter';
    'towing-air-tube-ring': 'Towing air tube ring';
    'towing-air-tube-ring-description': 'Inflatable ring for exciting towing activities';
    'transit-log': 'Transit log / Final cleaning';
    'transit-log-description': 'Charter pack including final cleaning and transit documentation';
    'underwater-scooter': 'Underwater scooter';
    'underwater-scooter-description': 'Motorized device for underwater exploration and fun';
    'vip-pack': 'VIP pack';
    'vip-pack-description': 'Premium service package with exclusive amenities';
    wakeboard: 'Wakeboard';
    'wakeboard-description': 'Board and equipment for wakeboarding water sports';
    'water-skies': 'Water skis';
    'water-skies-description': 'Equipment for water skiing behind the yacht or tender';
    'water-tube': 'Water tube';
    'water-tube-description': 'Inflatable tube for towing behind the yacht or tender';
    'wi-fi': 'Wi-Fi / Internet pack';
    'wi-fi-description': 'Internet connectivity during your charter';
  };
  form: {
    agency: {
      blacklisted: 'Blacklisted';
      discount: 'Maximum Discount (%)';
      email: 'Email';
      name: 'Name';
      phone: 'Phone Number';
      recommended: 'Recommended';
      skipExternalSystem: 'MMK / NauSys bypass';
      status: 'Status';
    };
    booking: {
      email: 'Email';
      external: 'External ID';
      'external-system': 'External System';
      reservation: 'Reservation';
      'reservation-number': 'Reservation number';
    };
    'custom-boat': {
      beam: 'Beam (m)';
      berths: 'Berths';
      boatModel: 'Boat model';
      boatName: 'Boat name';
      boatType: 'Boat Type';
      buildYear: 'Build Year';
      cabins: 'Cabins';
      'choose-equipment': 'Choose Equipment';
      country: 'Country';
      crewCabins: 'Crew Cabins';
      crewNumber: 'Crew Number';
      defaultCheckin: 'Default Check in';
      defaultCheckout: 'Default Check out';
      descriptionDe: 'Deutschland Description';
      descriptionEn: 'English Description';
      descriptionEs: 'Spanish Description';
      descriptionFr: 'French Description';
      descriptionHr: 'Croatia Description';
      descriptionIt: 'Italian Description';
      descriptionPt: 'Portuguese Description';
      draft: 'Draft (m)';
      enginePower: 'Engine';
      fuelTank: 'Fuel capacity (L)';
      genoaArea: 'Genoa Area';
      genoaType: 'Genoa Type';
      'input-country': 'Choose country';
      marina: 'Marina';
      inputMarina: 'Choose marina';
      selectCountryFirst: 'Choose country first';
      amenitiesText: 'Saloon and Cabins';
      amenitiesTextPlaceholder: string;
      toysText: 'Entertainment';
      toysTextPlaceholder: string;
      engineText: 'Engine';
      inputEngineText: string;
      inputBeam: 'Input beam';
      inputBerths: 'Input berths';
      inputBoatModel: 'Input boat model';
      inputBoatType: 'Input boat type';
      inputBuildYear: 'Input build year';
      inputCabins: 'Input cabins';
      inputCrewCabins: 'Input crew cabins';
      inputCrewNumber: 'Input crew number';
      inputDefaultCheckin: 'Input default check in';
      inputDefaultCheckout: 'Input default check out';
      inputDescription: 'Input description';
      inputDraft: 'Input draft';
      inputEnginePower: 'Input engine';
      inputFuelTank: 'Input fuel capacity';
      inputGenoaType: 'Input genoa type';
      inputLaunchYear: 'Input launch year';
      inputLength: 'Input lenght';
      inputMainsailType: 'Input mainsail type';
      inputManufacturer: 'Input manufacturer';
      inputMaxPersons: 'Input max persons';
      inputPrice: 'Input Price';
      inputPriceDescription: 'Input price description';
      inputVideoUrl: 'Input video link';
      inputWaterTank: 'Input water capacity';
      launchYear: 'Launch Year';
      length: 'Length (m)';
      mainsailArea: 'Mainsail Area';
      mainsailType: 'Mainsail Type';
      manufacturer: 'Manufacturer';
      manufacturerName: 'Manufacturer Name';
      maxPersons: 'Max Persons (Guests + Crew)';
      modelName: 'Model Name';
      price: 'Price (EUR - €)';
      priceDescription: 'Price description';
      videoUrl: 'Video link';
      waterTank: 'Water capacity (L)';
    };
    inquiry: {
      'choose-status': 'Choose status';
      status: 'Status';
    };
    invoice: {
      'include-vat': 'Include VAT';
      'input-invoice-item': 'Input item description';
      'input-price-without-vat': 'Input price without VAT';
      'input-recipient-city': 'Input City';
      'input-recipient-code': 'Input Zip Code';
      'input-recipient-country': 'Select Country';
      'input-recipient-name': 'Input Agency Name';
      'input-recipient-street': 'Input Street';
      'input-recipient-type': 'Select Type';
      'input-recipient-vat-code': 'Input Recipient VAT Code';
      'input-total-price': 'Input total price';
      'input-vat-amount': 'Input VAT amount';
      'input-vat-percentage': 'Input VAT percentage';
      'invoice-information': 'Invoice Information';
      'invoice-item': 'Item description';
      'price-ovverride-amount': 'Price override Amount';
      'price-without-vat': 'Price without VAT';
      'recipient-city': 'Recipient City';
      'recipient-code': 'Recipient Zip Code';
      'recipient-country': 'Recipient Country';
      'recipient-information': 'Recipient Information';
      'recipient-name': 'Recipient Name';
      'recipient-street': 'Recipient Street';
      'recipient-type': 'Recipient Type';
      'recipient-vat-code': 'Recipient VAT Code';
      'reservation-information': 'Reservation information';
      'select-language': 'Select Language';
      'select-status': 'Select status';
      'total-price': 'Total price';
      'vat-amount': 'VAT amout';
      'vat-percentage': 'VAT (%)';
    };
    user: {
      address: 'Address';
      'address-placeholder': 'Street and number';
      city: 'City';
      'choose-role': 'Choose Role';
      country: 'Country';
      email: 'Email';
      phone: 'Phone Number';
      role: 'Role';
      surname: 'Surname';
      'user-name': 'Name';
    };
  };
  inquiries: {
    'change-status': 'Change status';
    dates: 'Dates';
    'dates-not-specified': 'Dates not specified';
    email: 'Email Address';
    'full-name': 'Full Name';
    'manage-inquiry': 'Manage Inquiry';
    message: 'Message';
    phone: 'Phone Number';
    'send-offer': 'Send Offer';
    'user-info': 'User Info';
  };
  invoices: {
    'booking-details': {
      'booking-number': 'Booking number';
      'client-email': 'Client email';
      'client-name': 'Client name';
      'client-phone': 'Client phone number';
      'invoice-item': 'Item Description';
      title: 'Booking Details';
    };
    'invoice-details': {
      included: 'Included';
      'invoice-date': 'Date';
      'invoice-language': 'Language';
      'invoice-number': 'Invoice number';
      'invoice-vat': 'VAT';
      title: 'Invoice Details';
    };
    'pricing-details': {
      'price-without-vat': 'Price without VAT';
      title: 'Pricing';
      total: 'Total';
    };
    'recipient-details': {
      'recipient-city': 'City';
      'recipient-country': 'Country';
      'recipient-name': 'Name';
      'recipient-street': 'Street';
      'recipient-type': 'Type';
      'recipient-vat-code': 'VAT Code';
      'recipient-zip': 'Zip code';
      title: 'Recipient Details';
    };
  };
  login: {
    'back-to-login': 'Back to login';
    'email-address': 'Email';
    'forgotten-password': 'Forgotten password?';
    'log-in': 'Login';
    'logging-in': 'Logging in...';
    password: 'Password';
    'remember-me': 'Remember me';
    'reset-password': {
      button: 'Send reactivation code';
      'check-mailbox': 'Check your mailbox!';
      'check-mailbox-description': 'A code has been sent to email <strong>{{name}}</strong>';
      title: 'Reset Password';
    };
    'setup-password': {
      description: 'Input your new password.';
      'glad-you-back': 'Glad to have you back!';
      'password-reset-failed': 'Password reset code failed';
      'password-reset-failed-description': 'We are sorry, but your password reset code is either invalid or has expired. Please check the link or request a new password reset.';
      'repeat-password': 'Repeat password';
      'reset-password': 'Reset Password';
      'resetted-successfully': 'Password has been resetted successfully. Login below.';
      title: 'Setup New Password';
    };
    signup: {
      description: 'You’ve been invited to use Boat4You. Please finish up your profile below.';
      'invite-failed': 'Invite code failed';
      'invite-failed-description': ' We are sorry, but your invite is either invalid or has expired. Please check the link or request a new invitation.';
      'repeat-password': 'Repeat password';
      'sign-up': 'Sing up';
      'sign-up-failed': 'Failed to sign up';
      'sign-up-successfully': 'Signed up successfully';
      'signing-up': 'Signing Up...';
      title: 'Set up your account.';
    };
    title: 'Admin Panel Login';
    'toggle-password-visibility': 'Toggle password visibility';
  };
  navigation: {
    about: {
      title: 'About';
    };
    agencies: 'Agencies';
    bookings: 'Bookings';
    customBoats: 'Custom boats';
    extras: 'Extras';
    inquiries: 'Inquiries';
    invoices: 'Invoices';
    languagePicker: {
      languageLabel: 'Language';
      savePreferences: 'Save Preferences';
      title: 'Select Language';
    };
    logout: 'Logout';
    preferences: {
      language: 'Language';
      title: 'Preferences and profile';
    };
    profileSettings: 'Profile Settings';
    users: 'Users';
  };
  table: {
    agencies: {
      'by-pass': 'MMK/NauSys Bypass';
      email: 'Email';
      'max-discount': 'Max. Discount';
      name: 'Name';
      'phone-number': 'Phone Number';
      status: 'Status';
    };
    bookings: {
      'agency-price': 'Agency Price (€)';
      boat: 'Boat';
      'booking-date': 'Booking Date';
      'check-in': 'Check-In';
      'check-out': 'Check-Out';
      dates: 'Dates';
      ending: 'Ending';
      'net-price': 'Net Price (€)';
      'order-number': 'Order No.';
      price: 'Client Price (€)';
      route: 'Route';
      starting: 'Starting';
      status: 'Status';
      user: 'Client';
    };
    'custom-boats': {
      'high-price': 'High Price';
      location: 'Location';
      'low-price': 'Low Price';
      'mid-price': 'Mid Price';
      model: 'Model';
      name: 'Name';
    };
    extras: {
      description: 'Description';
      matchKeys: 'Match Keys';
      name: 'Name';
    };
    inquiries: {
      boat: 'Boat';
      'check-in': 'Check-In';
      'check-out': 'Check-Out';
      email: 'Email';
      'inquiries-number': 'Order No.';
      location: 'Location';
      name: 'Name';
      'phone-number': 'Phone Number';
      status: 'Status';
    };
    invoices: {
      client: 'Client';
      date: 'Date';
      email: 'Email';
      'invoices-number': 'Invoice No.';
      'phone-number': 'Phone Number';
      price: 'Price';
      'reservation-number': 'Reservation No.';
    };
    users: {
      email: 'Email';
      id: 'Client ID';
      name: 'Name';
      'phone-number': 'Phone Number';
      role: 'Role';
      status: 'Status';
      surname: 'Surname';
    };
  };
  tabs: {
    discounted: 'Discounted Boats';
    general: 'General';
  };
  'toast-messages': {
    'check-your-mailbox': 'Check your mailbox';
    'confirm-booking-failed': 'Failed to confirm booking';
    'confirm-booking-successfully': 'Confirm booking successfully';
    'create-custom-boat-failed': 'Create custom boat failed';
    'create-custom-boat-successfully': 'Create custom boat successfully';
    'create-invoice-failed': 'Failed to create invoice';
    'create-invoice-successfully': 'Create invoice successfully';
    'create-user-failed': 'Failed to create user';
    'create-user-successfully': 'Create user successful';
    'delete-booking-failed': 'Failed to cancel reservation';
    'delete-booking-successfully': 'Reservation cancelled successfully';
    'delete-custom-boat-failed': 'Failed to delete custom boat';
    'delete-custom-boat-successfully': 'Custom boat deleted successfully';
    'delete-image-failed': 'Failed to delete image';
    'delete-image-successfully': 'Image deleted successfully';
    'delete-images-failed': 'Failed to delete images';
    'delete-images-successfully': 'Images deleted successfully';
    'delete-invoice-failed': 'Failed to delete invoice';
    'delete-invoice-successfully': 'Delete invoice successfully';
    'delete-pdf-failed': 'Failed to delete PDF';
    'delete-pdf-successfully': 'PDF deleted successfully';
    'delete-user-failed': 'Failed to delete user';
    'delete-user-successfully': 'Delete user successful';
    'failed-to-send-email': 'Failed to send email';
    'invite-user-failed': 'Failed to invite user';
    'invite-user-successfully': 'Invite user successful';
    'login-failed': 'Login failed';
    'login-success': 'Login successful';
    'mark-paid-booking-failed': 'Failed to mark as paid booking';
    'mark-paid-booking-successfully': 'Mark as paid booking successfully';
    'save-notes-failed': 'Failed to save notes';
    'save-notes-successfully': 'Notes saved';
    'mark-sent-invoice-failed': 'Failed to mark as sent invoice';
    'mark-sent-invoice-successfully': 'Mark as Sent invoice successfully';
    'password-updated-failed': 'Failed to update password';
    'password-updated-successfully': 'Password updated successfully. Please log in again.';
    'profile-updated-failed': 'Failed to update profile';
    'profile-updated-successfully': 'Profile updated successfully';
    'surcharge-updated-failed': 'Unable to update card payment surcharge. Please try again.';
    'surcharge-updated-successfully': 'Card payment surcharge has been updated successfully';
    'sync-booking-failed': 'Failed to sync reservation';
    'sync-booking-successfully': 'Reservation synced successfully';
    'update-agency-failed': 'Update agency failed';
    'update-agency-successfully': 'Update agency successful';
    'update-custom-boat-failed': 'Failed to update custom boat';
    'update-custom-boat-successfully': 'Custom boat updated successfully';
    'update-inquiry-status-failed': 'Failed to change inquiry status';
    'update-inquiry-status-successfully': 'Inquiry status changed successfully';
    'update-invoice-failed': 'Failed to update invoice';
    'update-invoice-successfully': 'Update invoice successfully';
    'update-user-failed': 'Failed to update user';
    'update-user-successfully': 'Update user successful';
    'upload-image-failed': 'Failed to upload image';
    'upload-image-successfully': 'Image uploaded successfully';
    'upload-images-failed': 'Failed to upload images';
    'upload-images-successfully': 'Images uploaded successfully';
    'upload-pdf-failed': 'Failed to upload PDF';
    'upload-pdf-successfully': 'PDF uploaded successfully';
  };
  yacht: {
    allInclusive: 'All Inclusive';
    bareboat: 'Bareboat';
    catamaran: 'Catamaran';
    classicMainsail: 'Classic mainsail';
    crewed: 'Crewed';
    furlingGenoa: 'Furling Genoa';
    gulet: 'Gulet';
    luxuryMotorYacht: 'Luxury Motor Yacht';
    miniCruiser: 'Mini Cruiser';
    motorYacht: 'Motoryacht';
    motorboat: 'Motorboat';
    motorsailer: 'Motorsailer';
    powerCatamaran: 'Power Catamaran';
    rollingMainsail: 'Rolling mainsail';
    sailingYacht: 'Sailing Yacht';
    standardGenoa: 'Standard Genoa';
  };
}

export default Resources;
