/**
 * Marina → boat4you sailing-area resolver for the Offers workspace.
 *
 * MIRROR of boat4you-web src/helper/itineraryMatch.ts keyword tables
 * (condensed) — keep the two in sync when areas are added (same rule as
 * the payment-fee mirrors). The offer cart only knows marina NAMES and
 * a country NAME (not a code), so matching is keyword-based; `null`
 * means "no itinerary content for these waters — render nothing".
 */

const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  croatia: 'HR',
  greece: 'GR',
  italy: 'IT',
  spain: 'ES',
  turkey: 'TR',
  turkiye: 'TR',
  'british virgin islands': 'VG',
  'virgin islands (british)': 'VG',
  bahamas: 'BS',
  grenada: 'GD',
  martinique: 'MQ',
  'saint lucia': 'LC',
  'st. lucia': 'LC',
};

const AREA_KEYWORDS: Record<string, [string, string[]][]> = {
  HR: [
    [
      'sibenik',
      [
        'sibenik',
        'mandalina',
        'kremik',
        'pirovac',
        'rogoznica',
        'frapa',
        'skradin',
        'primosten',
        'vodice',
        'jezera',
        'murter',
        'betina',
        'tribunj',
        'hramina',
        'solaris',
      ],
    ],
    [
      'zadar',
      [
        'zadar',
        'sukosan',
        'dalmacija',
        'biograd',
        'kornati',
        'pag ',
        'preko',
        'sangulin',
        'kukljica',
        'simuni',
        'novalja',
        'olive island',
        'ugljan',
        'pasman',
        'sali',
        'borik',
      ],
    ],
    ['dubrovnik', ['dubrovnik', 'slano', 'komolac', 'cavtat', 'orebic', 'korcula', 'lumbarda', 'ploce', 'gruz']],
    [
      'istria',
      [
        'pula',
        'pomer',
        'veruda',
        'rovinj',
        'porec',
        'vrsar',
        'umag',
        'novigrad',
        'punat',
        'krk',
        'opatija',
        'rijeka',
        'icici',
        'cres',
        'losinj',
        'rab',
        'kvarner',
        'crikvenica',
        'njivice',
        'malinska',
        'polesana',
        'medulin',
        'admiral',
      ],
    ],
    [
      'split',
      [
        'split',
        'trogir',
        'kastel',
        'seget',
        'baotic',
        'agana',
        'rogac',
        'milna',
        'supetar',
        'bol',
        'hvar',
        'vrboska',
        'jelsa',
        'stari grad',
        'makarska',
        'baska voda',
        'omis',
        'strozanac',
        'podstrana',
        'lav ',
        'vranjic',
        'stobrec',
        'vis ',
        'komiza',
        'vela luka',
        'maslinica',
      ],
    ],
  ],
  GR: [
    [
      'ionian',
      [
        'lefkas',
        'lefkada',
        'corfu',
        'gouvia',
        'kerkyra',
        'preveza',
        'aktio',
        'zakynthos',
        'kefalonia',
        'argostoli',
        'ithaki',
        'ithaca',
        'vounaki',
        'palairos',
        'nidri',
        'nikiana',
        'sivota',
        'plataria',
        'parga',
        'paleros',
        'vliho',
      ],
    ],
    ['sporades', ['volos', 'skiathos', 'skopelos', 'alonissos', 'achilleio', 'nea anchialos', 'nies', 'milina']],
    [
      'dodecanese',
      ['kos', 'rhodes', 'rodos', 'samos', 'pythagorio', 'leros', 'lakki', 'kalymnos', 'symi', 'karpathos', 'patmos'],
    ],
    [
      'cyclades',
      [
        'alimos',
        'athens',
        'athina',
        'kalamaki',
        'lavrio',
        'lavrion',
        'laurium',
        'olympic',
        'agios kosmas',
        'flisvos',
        'zea',
        'piraeus',
        'paros',
        'naxos',
        'mykonos',
        'syros',
        'santorini',
        'milos',
        'sifnos',
        'kythnos',
        'kea',
        'aegina',
        'poros',
        'hydra',
        'spetses',
        'ermioni',
        'porto heli',
        'nafplio',
        'methana',
        'nea peramos',
        'sounio',
        'vouliagmeni',
        'glyfada',
        'salamina',
        'salamis',
        'chalkida',
        'evia',
        'loutraki',
        'kilada',
        'tolo',
      ],
    ],
  ],
  IT: [
    [
      'sicily',
      [
        'sicil',
        'palermo',
        'portorosa',
        'orlando',
        'lipari',
        'milazzo',
        'marsala',
        'trapani',
        'riposto',
        'catania',
        'siracusa',
        'cefalu',
        'aeolian',
        'favignana',
        'salina',
        'messina',
      ],
    ],
    [
      'sardinia',
      [
        'sardin',
        'olbia',
        'portisco',
        'cannigione',
        'cala dei sardi',
        'carloforte',
        'cagliari',
        'alghero',
        'palau',
        'maddalena',
        'santa teresa',
        'villasimius',
        'arbatax',
        'castelsardo',
        'porto cervo',
        'porto rotondo',
        'golfo aranci',
      ],
    ],
    [
      'amalfi',
      [
        'salerno',
        'arechi',
        'napoli',
        'naples',
        'procida',
        'ischia',
        'capri',
        'sorrento',
        'castellammare',
        'stabia',
        'amalfi',
        'positano',
        'pozzuoli',
        'genova',
        'genoa',
        'lavagna',
        'portofino',
        'chiavari',
        'rapallo',
        'sestri',
        'imperia',
        'loano',
        'varazze',
        'savona',
        'la spezia',
        'lerici',
        'viareggio',
        'livorno',
        'punta ala',
        'argentario',
        'porto ercole',
        'santo stefano',
        'elba',
        'portoferraio',
        'piombino',
        'scarlino',
        'cala de',
        'civitavecchia',
        'ostia',
        'roma',
        'anzio',
        'nettuno',
        'gaeta',
        'formia',
        'terracina',
        'san felice',
        'ponza',
        'tropea',
        'gallipoli',
        'otranto',
        'brindisi',
        'bari',
        'monopoli',
      ],
    ],
  ],
  ES: [
    ['ibiza', ['ibiza', 'eivissa', 'sant antoni', 'san antonio', 'formentera', 'santa eulalia', 'botafoch']],
    [
      'mallorca',
      [
        'mallorca',
        'palma',
        'la lonja',
        'alcudia',
        'pollensa',
        'portocolom',
        'porto colom',
        'andratx',
        'soller',
        'porto cristo',
        'arenal',
        'can pastilla',
        'menorca',
        'mahon',
        'ciutadella',
        'fornells',
        'naviera',
        'portals',
        'santa ponsa',
        'bonaire',
        'calanova',
      ],
    ],
    [
      'catalonia',
      [
        'barcelona',
        'badalona',
        'sitges',
        'palamos',
        'roses',
        'estartit',
        'empuriabrava',
        'blanes',
        'mataro',
        'vilanova',
        'tarragona',
        'cambrils',
        'sant carles',
        'garraf',
        'ginesta',
        'castelldefels',
        'denia',
        'javea',
        'calpe',
        'altea',
        'alicante',
        'torrevieja',
        'valencia',
        'gandia',
        'castellon',
      ],
    ],
  ],
  TR: [
    [
      'bodrum',
      [
        'bodrum',
        'turgutreis',
        'yalikavak',
        'didim',
        'turkbuku',
        'gumusluk',
        'milta',
        'kusadasi',
        'izmir',
        'cesme',
        'alacati',
        'sigacik',
      ],
    ],
    [
      'gocek',
      [
        'gocek',
        'fethiye',
        'ece ',
        'skopea',
        'marmaris',
        'netsel',
        'albatros',
        'adakoy',
        'orhaniye',
        'selimiye',
        'bozburun',
        'datca',
        'hisaronu',
        'kas ',
        'kalkan',
        'finike',
        'kemer',
        'antalya',
      ],
    ],
  ],
  VG: [
    [
      'bvi',
      [
        'tortola',
        'nanny cay',
        'road town',
        'hodge',
        'soper',
        'virgin gorda',
        'spanish town',
        'jost',
        'scrub island',
        'trellis',
        'beef island',
      ],
    ],
  ],
  BS: [
    [
      'bahamas',
      [
        'nassau',
        'marsh harbour',
        'abaco',
        'palm cay',
        'exuma',
        'george town',
        'bimini',
        'freeport',
        'hope town',
        'treasure cay',
        'eleuthera',
        'staniel',
      ],
    ],
  ],
  GD: [
    [
      'grenada',
      [
        'grenada',
        'port louis',
        'st george',
        'saint george',
        'prickly bay',
        'clarkes court',
        'phare bleu',
        'secret harbour',
        'carriacou',
      ],
    ],
  ],
  MQ: [
    [
      'martinique',
      ['martinique', 'le marin', 'fort de france', 'fort-de-france', 'pointe du bout', 'case pilote', 'trois ilets'],
    ],
  ],
  LC: [['martinique', ['rodney bay', 'castries', 'soufriere', 'vieux fort']]],
};

const COUNTRY_DEFAULT_AREA: Record<string, string> = {
  HR: 'split',
  GR: 'cyclades',
  VG: 'bvi',
  BS: 'bahamas',
  GD: 'grenada',
  MQ: 'martinique',
};

const normalize = (s: string) => s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');

/** Resolve marina/base names + country NAME to a boat4you itinerary area id (or null). */
export const itineraryAreaFor = (
  marinaNames: (string | null | undefined)[],
  countryName: string | null | undefined
): string | null => {
  const haystack = ` ${marinaNames
    .filter(Boolean)
    .map(n => normalize(n as string))
    .join(' | ')} `;

  if (haystack.trim() === '|' || haystack.trim() === '') return null;

  const cc = countryName ? (COUNTRY_NAME_TO_CODE[normalize(countryName)] ?? '') : '';

  const matchIn = (tables: [string, string[]][]): string | null =>
    tables.find(([, keywords]) => keywords.some(k => haystack.includes(k)))?.[0] ?? null;

  return (
    matchIn(AREA_KEYWORDS[cc] ?? []) ??
    Object.values(AREA_KEYWORDS).map(matchIn).find(Boolean) ??
    COUNTRY_DEFAULT_AREA[cc] ??
    null
  );
};

/** Public boat4you URL of the area's itinerary landing, or null. */
export const itineraryAreaUrl = (
  marinaNames: (string | null | undefined)[],
  countryName: string | null | undefined
): string | null => {
  const area = itineraryAreaFor(marinaNames, countryName);

  return area ? `https://www.boat4you.com/itineraries/${area}` : null;
};
