import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';

import { Box, Button, Stack, Typography } from '@mui/material';
import QRCode from 'qrcode';

import { bbColors } from '@/styles/bb';

interface BookingTripHubProps {
  tripToken: string | null | undefined;
}

/**
 * Boat4You Trip hub panel — the customer's PWA link for this booking. Mario
 * copies the link (WhatsApp/e-mail) or shows/sends the QR; scanning it on a
 * phone opens the trip hub ready to be added to the home screen. The token is
 * generated by the backend for every reservation (V9_28).
 */
const CUSTOMER_WEB_URL = import.meta.env.VITE_CUSTOMER_WEB_URL || 'http://localhost:3000';

const BookingTripHub = ({ tripToken }: BookingTripHubProps) => {
  const { t } = useTranslation();
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const tripUrl = tripToken ? `${CUSTOMER_WEB_URL}/trip/${tripToken}` : null;

  useEffect(() => {
    if (!tripUrl) return;

    QRCode.toDataURL(tripUrl, { width: 320, margin: 1, color: { dark: '#0c2461', light: '#ffffff' } })
      .then(setQrDataUrl)
      // eslint-disable-next-line no-console
      .catch(err => console.error('[trip-hub] QR generation failed', err));
  }, [tripUrl]);

  if (!tripUrl) return null;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(tripUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      // Clipboard unavailable (http/permissions) — the input below stays selectable.
    }
  };

  return (
    <Stack spacing={1} sx={{ pt: 2.5 }}>
      <Typography
        variant="body2"
        fontWeight={700}
        color={bbColors.gray500}
        sx={{ textTransform: 'uppercase', letterSpacing: 0.6, fontSize: 11 }}
      >
        {t('booking.trip-hub', 'Trip app (PWA)')}
      </Typography>

      <Box
        sx={{
          border: `1px solid ${bbColors.gray200}`,
          borderRadius: '8px',
          background: '#fff',
          p: 1.5,
          display: 'flex',
          gap: 1.5,
          alignItems: 'center',
        }}
      >
        {qrDataUrl && (
          <img
            src={qrDataUrl}
            alt="Trip hub QR"
            width={96}
            height={96}
            style={{ borderRadius: 6, flexShrink: 0 }}
          />
        )}
        <Stack spacing={0.75} sx={{ minWidth: 0, flex: 1 }}>
          <Typography sx={{ fontSize: 11, color: bbColors.gray500, wordBreak: 'break-all', lineHeight: 1.4 }}>
            {tripUrl}
          </Typography>
          <Stack direction="row" spacing={1}>
            <Button
              size="small"
              variant="contained"
              onClick={handleCopy}
              sx={{ textTransform: 'none', fontSize: 12, borderRadius: '6px' }}
            >
              {copied ? t('booking.copied', 'Copied ✓') : t('booking.copy-link', 'Copy link')}
            </Button>
            <Button
              size="small"
              variant="outlined"
              component="a"
              href={tripUrl}
              target="_blank"
              rel="noopener noreferrer"
              sx={{ textTransform: 'none', fontSize: 12, borderRadius: '6px' }}
            >
              {t('booking.open', 'Open ↗')}
            </Button>
          </Stack>
          <Typography sx={{ fontSize: 10.5, color: bbColors.gray500 }}>
            {t(
              'booking.trip-hub-hint',
              'Customer scans the QR on a phone → adds the trip to the home screen. Crew-shareable; no prices shown.',
            )}
          </Typography>
        </Stack>
      </Box>
    </Stack>
  );
};

export default BookingTripHub;
